
## packages

```{r}
library(tidyverse)
library(seaiceR)
library(conflicted)
conflict_prefer("filter", "dplyr")
```

## datasets

```{r}
datasets <- c("ArcticBay", "FoxeBasin", "HudsonBay", "HudsonStrait")
suffixes <- c("Brkup", "Frzup", "Icefree")
extensions <- ".csv"
d <- crossing(datasets, type=suffixes, extensions)
d %>% mutate(fname = str_c(datasets, "_", type, extensions)) -> all_data
all_data
```

read in

```{r}
all_data %>% 
  rowwise() %>% 
  mutate(data = list(read_csv(fname))) %>% 
  unnest(data) -> all_data
all_data
```

breakups

```{r}
all_data %>% filter(type == "Frzup") %>% 
  rename(Year = X1) %>% 
  pivot_longer(`1`:`36`, names_to = "location", values_to = "date") %>% 
  drop_na() %>% 
  mutate(location = str_c(datasets, location)) %>% 
  select(Year, location, date) %>% 
  pivot_wider(names_from = Year, values_from = date) -> this_data
this_data
this_data %>% 
  dist() -> my_dist
```

feed that into hclust

```{r}
n_clusters <- 8
d.1 <- hclust(my_dist, method = "ward.D")
plot(d.1, labels = this_data$location)
rect.hclust(d.1, n_clusters)
```
pop out graph, blow it up


```{r}
tibble(location = this_data$location, cluster = cutree(d.1, n_clusters)) %>% 
  extract(location, into = "dataset", regex = "([A-Za-z]+)[0-9]+$", remove = FALSE) %>% 
  with(., table(dataset, cluster))
```

